# Generated by Django 3.1.4 on 2021-01-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbaleri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num_vies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='num_vies',
            field=models.IntegerField(default=0),
        ),
    ]
