# Generated by Django 3.1.4 on 2021-01-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbaleri', '0002_auto_20210103_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
