# Generated by Django 3.1.4 on 2021-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbaleri', '0003_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='num_vies',
            new_name='num_views',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
